### PR TITLE
Fix bucket spilling on foreign islands

### LINKED ISSUE #497: [BUG] Other players can place lava and water
players that do not have permission can install water and lava on other people's islands.

### PR DESCRIPTION
**Pull request by dlsf**
Temporarily fixes #497

### CODE REVIEW

File: src/main/java/com/iridium/iridiumskyblock/listeners/PlayerBucketEmptyListener.java [hunk 1]
```diff
@@ -37,6 +40,14 @@ public void onBucketEmpty(PlayerBucketEmptyEvent event) {
                 return;
             }
         }
+
+        // Temporary fix until https://hub.spigotmc.org/jira/browse/SPIGOT-6351 is fixed
+        User user = User.getUser(event.getPlayer());
+        Island island = IslandManager.getIslandViaLocation(block.getLocation());
+        if (user.getIsland() != null && user.islandID != island.id && !island.isCoop(user.getIsland())) {
```
Comment (MertUnverdi) [inline src/main/java/com/iridium/iridiumskyblock/listeners/PlayerBucketEmptyListener.java:47]: add island != null
