### PR TITLE
Fix island being not visitable for coop members (#484)

### LINKED ISSUE #484: [BUG] visit problem between coop islands
After you have signed an island coop, you cannot go to an island that is private. Just like other visitors, the message that you cannot move is printed. / is coop command if you teleport using the same.

bad eng sorry, I used the translator.

### PR DESCRIPTION
**Pull request by dlsf**
Fixes #484 by letting coop members join a coop island, regardless if it's private. Also introduces a config option for people who want the old behavior.

### CODE REVIEW

File: src/main/java/com/iridium/iridiumskyblock/User.java [hunk 1]
```diff
@@ -107,4 +107,12 @@ public void clearHolograms() {
     public void save(Connection connection) {
         UserManager.saveUser(this, connection);
     }
+
+    public boolean hasCoopVisitPermissions(User otherUser) {
```
Comment (PeachesMLG) [inline src/main/java/com/iridium/iridiumskyblock/User.java:111]: Wouldnt it make more sence to put this in the Island class?

**Review by PeachesMLG — CHANGES_REQUESTED** [review]

File: src/main/java/com/iridium/iridiumskyblock/User.java (hunk 1 above)
Comment (dlsf) [reply src/main/java/com/iridium/iridiumskyblock/User.java:111]: Well, a user can visit another user, so it makes sense that it's in the User class. I mean... At least the way I made it, it's user-specific behavior.
