### PR TITLE
Fixed issues with InteractEvent

### LINKED ISSUE #348: Visitors can pickup or place armors in armorstands (No protection)
Every player, like visitors can pickup all armors from all armorstands in other's islands. It doesn't have any protection for armorstands. And there is no option for it in island permissions (I tried to disable all of that)
I'm on Paper-1.12.2, Using the latest version of IridiumSkyblock.

**To Reproduce**
1. Go to a player's island that has armorstands.
2. Find the armorstand
3. Simply right click and pickup all armors, or if you want you can be generous and place armors there.

### PR DESCRIPTION
**Pull request by MertUnverdi**
Fixed #348 now visitors can't pickup items from itemframe and armorstand

### CODE REVIEW

**Comment by MertUnverdi** [comment]
i saw imports (intellij auto changing it) i'll change it to back on next PR 👍

File: src/main/java/com/iridium/iridiumskyblock/listeners/PlayerInteractListener.java [hunk 1]
```diff
@@ -6,8 +6,9 @@
 import org.bukkit.block.Block;
 import org.bukkit.entity.Entity;
 import org.bukkit.entity.Player;
-import org.bukkit.event.EventHandler;
-import org.bukkit.event.Listener;
+import org.bukkit.event.*;
```
Comment (IridiumLLC) [inline src/main/java/com/iridium/iridiumskyblock/listeners/PlayerInteractListener.java:9]: Dont do * imports

File: src/main/java/com/iridium/iridiumskyblock/listeners/PlayerInteractListener.java [hunk 2]
```diff
@@ -25,8 +26,8 @@ public void onPlayerInteract(PlayerInteractEvent event) {
             final User user = User.getUser(player);
             final Block block = event.getClickedBlock();
 
-            if (event.getAction().toString().startsWith("RIGHT_CLICK")) {
-                if (player.getItemInHand() != null) {
+            if (event.getAction() == Action.RIGHT_CLICK_BLOCK || event.getAction() == Action.RIGHT_CLICK_AIR) {
+                if (player.getItemInHand().equals(IridiumSkyblock.getInventories().crystal.material.parseItem())) {
```
Comment (IridiumLLC) [inline src/main/java/com/iridium/iridiumskyblock/listeners/PlayerInteractListener.java:30]: Dont do this, since each crystal will be different depending on how many crystals the item contains. The method below

```
if (crystals != 0){
```
This will filter out if they are holding a crystal item
```

**Review by IridiumLLC — CHANGES_REQUESTED** [review]

File: src/main/java/com/iridium/iridiumskyblock/listeners/PlayerInteractListener.java (hunk 1 above)
Comment (MertUnverdi) [reply src/main/java/com/iridium/iridiumskyblock/listeners/PlayerInteractListener.java:9]: https://github.com/IridiumLLC/IridiumSkyblock/pull/351#issuecomment-723575740
As i said :)
