### PR TITLE
Limitedblock fix

### LINKED ISSUE #424: [BUG]
**Describe the bug**
I'm having a issue with Iridium, basically when there is a certain block limit defined in config, lets say the one that comes by default, which is HOPPER (10), when you place those hoppers and remove them, your limit doesn't reset and you can't place any more hoppers, same happens with other blocks.

**To Reproduce**
1. Install Iridium
2. Place 10 hoppers
3. Remove them
4. Try placing them again

**Console Error**
If applicable, a pastebin link of any console errors

**Screenshots**

### PR DESCRIPTION
**Pull request by CW-UK**
Updates island when blocks in limitedBlocks are broken to allow re-placing without waiting for a scheduled recalculation.

Fixes #424

### CODE REVIEW

File: src/main/java/com/iridium/iridiumskyblock/listeners/BlockBreakListener.java [hunk 1]
```diff
@@ -83,7 +83,9 @@ public void onMonitorBreakBlock(BlockBreakEvent event) {
             final Island island = islandManager.getIslandViaLocation(location);
             if (island == null) return;
 
-            if (Utils.isBlockValuable(block)) {
+            final XMaterial xmaterial = XMaterial.matchXMaterial(block.getType());
```
Comment (PeachesMLG) [inline src/main/java/com/iridium/iridiumskyblock/listeners/BlockBreakListener.java:86]: This is a duplicate to line 89

File: src/main/java/com/iridium/iridiumskyblock/listeners/BlockBreakListener.java [hunk 2]
```diff
@@ -83,7 +83,9 @@ public void onMonitorBreakBlock(BlockBreakEvent event) {
...
+            final Integer limitedMax = IridiumSkyblock.getConfiguration().limitedBlocks.get(xmaterial);
+            if (Utils.isBlockValuable(block) || limitedMax != null) {
```
Comment (PeachesMLG) [inline src/main/java/com/iridium/iridiumskyblock/listeners/BlockBreakListener.java:88]: change to IridiumSkyblock.getConfiguration().limitedBlocks.contains() since we arnt using the size for anything

**Review by PeachesMLG — CHANGES_REQUESTED** [review]
